export const STUDENT_API = import.meta.env.VITE_STUDENT_API
export const STUDENT_PLACEMENT_DETAILS_API = import.meta.env.VITE_STUDENT_PLACEMENT_DETAILS_API
export const STUDENT_INTERN_DETAILS_API = import.meta.env.VITE_STUDENT_INTERN_DETAILS_API
export const STUDENT_NOT_SITTING_DETAILS_API = import.meta.env.VITE_STUDENT_NOT_SITTING_DETAILS_API
export const EXPERIENCE_API = import.meta.env.VITE_EXPERIENCE_API
export const DRIVES_API = import.meta.env.VITE_DRIVES_API
