export const STUDENT_API = import.meta.env.VITE_STUDENT_API
export const EXPERIENCES_API = import.meta.env.VITE_EXPERIENCES_API
export const DRIVES_API = import.meta.env.VITE_DRIVES_API
export const COMPANIES_LIST_API = import.meta.env.VITE_COMPANIES_LIST_API
export const COMPANIES_API = import.meta.env.VITE_COMPANIES_API
export const STATISTICS_API = import.meta.env.VITE_STATISTICS_API
export const RECENT_NOTIFICATIONS_API = import.meta.env.VITE_RECENT_NOTIFICATIONS_API
export const DASHBOARD_API = import.meta.env.VITE_DASHBOARD_API
export const ROLES_API = import.meta.env.VITE_ROLES_API
export const COMPANIES_ORDERWISE_API = import.meta.env.VITE_COMPANIES_ORDERWISE_API
export const CLUSTERS_API = import.meta.env.VITE_CLUSTERS_API
export const RESOURCES_API = import.meta.env.VITE_RESOURCES_API
export const STATES_API = import.meta.env.VITE_STATES_API
export const CITIES_API = import.meta.env.VITE_CITIES_API
export const COURSES_API = import.meta.env.VITE_COURSES_API
export const BRANCHES_API = import.meta.env.VITE_BRANCHES_API
export const STATISTICS_DETAILS_API = import.meta.env.VITE_STATISTICS_DETAILS_API
export const STUDENT_LOGIN_API = import.meta.env.VITE_STUDENT_LOGIN_API
export const STUDENT_REGISTER_API = import.meta.env.VITE_STUDENT_REGISTER_API
export const STUDENT_OTP_API = import.meta.env.VITE_STUDENT_OTP_API
export const STUDENT_ELIGIBILITY_API = import.meta.env.VITE_STUDENT_ELIGIBILITY_API
export const STUDENT_LOGOUT_API = import.meta.env.VITE_STUDENT_LOGOUT_API
export const REFRESH_TOKEN_API = import.meta.env.VITE_REFRESH_TOKEN_API
export const TPO_STATS_API = import.meta.env.VITE_TPO_STATS_API
export const RECENT_EXPERIENCE_API = import.meta.env.VITE_RECENT_EXPERIENCE_API
export const COMPANY_WISE_STATS_API = import.meta.env.VITE_COMPANY_WISE_STATS_API
export const PERCENTAGE_ELIGIBILITY_API = import.meta.env.VITE_PERCENTAGE_ELIGIBILITY_API
export const TPO_DRIVES_API = import.meta.env.VITE_TPO_DRIVES_API
export const ELIGIBLE_STUDENTS_API = import.meta.env.VITE_ELIGIBLE_STUDENTS_API
export const ON_CAMPUS_API = import.meta.env.VITE_ON_CAMPUS_API
export const OFF_CAMPUS_API = import.meta.env.VITE_OFF_CAMPUS_API
export const PPO_API = import.meta.env.VITE_PPO_API
export const enum Role {
  TPO = 'TPO',
  TPR = 'TPR',
  STUDENT = 'STUDENT',
}
